### ISSUE TITLE
Реализуйте функцию isPrime определяющую, является ли число простым.

### ISSUE THREAD

**Issue by inquiring** [Hexlet/code-reviews#3]
function isPrime($number){
    for($x = 2; $x <= sqrt($number); $x++){
        if($number % $x == 0){
            return false;
        }
    }
    return true;
}

**Comment by mokevnin** [comment]
Чтобы не повторяться, посмотрите это ревью: https://github.com/Hexlet/code-reviews/blob/master/02.php.md

И при вставке кода в issue, пользуйтесь markdown чтобы было форматирование.

**Comment by ASuleymanov** [comment]
подскажите, пж, как пользоваться markdown. Я здесь первый раз. Сложно сориентироваться. Я скачал его. он упал в загрузки, а что дальше не знаю((

**Comment by inquiring** [comment]
```
function isPrime($number) {
  for ($x = 2; $x <= sqrt($number); $x++) {
    if ($number == 0) {
     return false;
    }
     return true;
  }
};
```
